version: 1.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  TARGET_CONFIGURATION: Release
build_script:
- cmd: >-
    dotnet build -p:Version=%APPVEYOR_BUILD_VERSION% --configuration %TARGET_CONFIGURATION%
    
    appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%/SabberStone/bin/Release/SabberStone.%APPVEYOR_BUILD_VERSION%.nupkg -FileName SabberStone.%APPVEYOR_BUILD_VERSION%.nupkg -DeploymentName SabberStone
 
test_script:
- cmd: >-
    dotnet test --configuration Release ./SabberStoneCoreTest
    
deploy:
- provider: NuGet
  api_key:
    secure: qR9SWQUPkiYwFQKvljIajuoDvjS4rDAHkYVY1QaFP3yRqRoEp+LF/Um2v2Y4LqcN
  artifact: /.*.nupkg/
