version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
pull_requests:
  do_not_increment_build_number: true

# Can't change default email notifications without providing
# e-mail addresses.

cache:
- './packages'

# Only build when the following files were changed
only_commits:
  files:
  - '**/*.cs'

before_build:
- cmd:
  - REM Restore packages for all projects within solution
  - nuget.exe restore

build:
  project: SabberStone.sln
  parallel: true
  verbosity: minimal

test_script:
- cmd:
  - REM Run the test project (.NET Core)
  - cd ./SabberStoneCoreTest
  - dotnet xunit
artifacts:
- path: SabberStoneCore\bin\**\Release\**\SabberStoneCore.xml
  name: SabberStoneCore doc
- path: SabberStoneCore\bin\**\Release\**\*.dll
  name: SabberStoneCore libs
